version = 1

# Define test file patterns - DeepSource will apply different rules to these files
test_patterns = [
  "**/__tests__/**",
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/test-*.ts",
  "src/__tests__/**"
]

# Exclude files from analysis entirely
exclude_patterns = [
  "coverage/**",
  "dist/**",
  "build/**",
  "out/**",
  "node_modules/**",
  ".nyc_output/**",
  "*.config.js",
  "*.config.ts",
  "jest.setup.ts",
  "vitest.setup.ts",
  "docs/**",
  "examples/**",
  "scripts/**"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  dialect = "typescript"